version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    reviewers:
      - 'contentful/team-extensibility'
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=15.0.0"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    directory: '/'
