const DOTENV_FILE = '.env';
const ACCESS_TOKEN_ENV_KEY = 'CONTENTFUL_ACCESS_TOKEN';
const ORG_ID_ENV_KEY = 'CONTENTFUL_ORG_ID';
const APP_DEF_ENV_KEY = 'CONTENTFUL_APP_DEF_ID';

module.exports = {
  DOTENV_FILE,
  ACCESS_TOKEN_ENV_KEY,
  ORG_ID_ENV_KEY,
  APP_DEF_ENV_KEY,
}
