const DOTENV_FILE = '.env';
const ACCESS_TOKEN_ENV_KEY = 'CONTENTFUL_ACCESS_TOKEN';
const ORG_ID_ENV_KEY = 'CONTENTFUL_ORG_ID';
const APP_DEF_ENV_KEY = 'CONTENTFUL_APP_DEF_ID';

const DEFAULT_BUNDLES_TO_KEEP = 50;
const DEFAULT_BUNDLES_TO_FETCH = 1000;
const MAX_CONCURRENT_DELETION_CALLS = 5;

const CONTENTFUL_API_HOST = 'api.contentful.com';

module.exports = {
  DOTENV_FILE,
  ACCESS_TOKEN_ENV_KEY,
  ORG_ID_ENV_KEY,
  APP_DEF_ENV_KEY,
  DEFAULT_BUNDLES_TO_KEEP,
  DEFAULT_BUNDLES_TO_FETCH,
  MAX_CONCURRENT_DELETION_CALLS,
  CONTENTFUL_API_HOST,
};
