#! /usr/bin/env node

const path = require('path')
const fs = require('fs');
const { printErrorAndExit, printInfo, SANDBOX_PATH, TEMPLATE_PATH, printHeader, printSuccess, validateAndRequire } = require('./utils');

const manifestPath = path.join(SANDBOX_PATH, 'package.json');

printHeader(`Creating manifest at ${manifestPath}`);

if (!fs.existsSync(SANDBOX_PATH)) {
  printErrorAndExit(`Unable to find sandbox environment at ${SANDBOX_PATH}`);
}

const template = validateAndRequire(TEMPLATE_PATH);

// Create in memory manifest
const manifest = {
  name: "test",
  version: "0.0.1",
  private: true,
  dependencies: template.package.dependencies
}

try {
  printInfo(`Writing manifest...`)
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2))
  printSuccess('Successfully created manifest')
} catch (e) {
  printErrorAndExit(`Unable to write ${manifestPath}`, e);
}
