name: CI

permissions:
  contents: read
  actions: read

on:
  push:
    branches: [main, canary]
  pull_request:
    branches: [main, canary]

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
