name: Test functions

on:
  workflow_call:`

jobs:
  test-functions:
    strategy:
      matrix:
        node-version: [18.20, 20.18, 22.11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      actions: read

    steps:
      - uses: ./.github/actions/install-and-build
        with:
          os: ${{ matrix.os }}
          node-version: ${{ matrix.node-version }}

      - name: Test built functions (Unix)
        if: matrix.os == 'ubuntu-latest'
        run: |
          FORMER_CWD="$(pwd)"
          PROJECT=test-$(date +%s)
          mkdir "/tmp/${PROJECT}"
          cd "/tmp/${PROJECT}"
          node "${FORMER_CWD}/packages/contentful--create-contentful-app/lib/index.js" my-function --function external-references
          cd my-function   
          node "${FORMER_CWD}/packages/contentful--app-scripts/lib/bin.js" build-functions --ci

      - name: Test built functions (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $FORMER_CWD = (Get-Location).Path
          $PROJECT = "test-" + [DateTimeOffset]::Now.ToUnixTimeSeconds()
          $TEMP_DIR = [System.IO.Path]::GetTempPath()
          $PROJECT_PATH = Join-Path $TEMP_DIR $PROJECT
          New-Item -ItemType Directory -Path $PROJECT_PATH
          Set-Location $PROJECT_PATH
          node (Join-Path $FORMER_CWD "packages/contentful--create-contentful-app/lib/index.js") my-function --function external-references
          Set-Location my-function
          node (Join-Path $FORMER_CWD "packages/contentful--app-scripts/lib/bin.js") build-functions --ci
